// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("LFEG.Sample")]
[assembly: AssemblyProductAttribute("LFEG")]
[assembly: AssemblyDescriptionAttribute("LFEG - Lighting Fast Excel Generator, a framework for efficient generation of excel files")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
